---
title: "Summarizing and Transforming Data in R"
author: "Fadel"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_download: TRUE
    code_folding: show
    number_sections: TRUE
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summarizing Data

## R

```{r gme_example_r}
gme_get = 
  tidyquant::tq_get(x = 'GME', from = '2019-06-01', to = '2020-03-16') |> 
  dplyr::select(date, symbol, adjusted) |> 
  dplyr::mutate(
    year = lubridate::year(date), 
    month = lubridate::month(date, label = T)
  )

gme_summary = 
  gme_get |> 
  dplyr::group_by(symbol, year, month) |>
  dplyr::summarise( 
    ajusted_avg = mean(adjusted), 
    adjusted_med = median(adjusted), 
    adjusted_var = var(adjusted), 
    adjusted_sd = sd(adjusted) 
  )
print(gme_summary, n=15)
```


## Python

```{python gme_example_py}
import pandas as pd
import yfinance as yf
import datetime as dt

# getting the data
gme_df = yf.download('GME', start = '2019-06-01', end = '2020-03-13')
gme_df = gme_df.reset_index() # to create the Date col from the index

# create the month and year columns from my df
gme_df['year'] = gme_df['Date'].dt.year
gme_df['month'] = gme_df['Date'].dt.month_name()

# Summaries on the adjusted (Adj Close) column
# R: group_by |> summarize
# Py: groupby.agg
gme_summary = gme_df.groupby(['year', 'month']).agg({
  'Adj Close': [
    'mean',
    'median',
    'var',
    'std',
    lambda x: x.max() - x.min(), # range
    lambda x: (x - x.mean()).abs().mean()
]
})

gme_summary.reset_index(inplace = True)

gme_summary.columns = ['year', 'month', 'adj_mean', 'adj_median', 'adj_var', 'adj_std', 'adj_range', 'adj_mad']

gme_summary.tail()
```


# Transformations

## R

```{r transformations_r}
women_df = readr::read_csv('murdered_women_per_100000_people.csv') |> 
  tidyr::pivot_longer(cols = 2:68, names_to = 'year', values_to = 'women_murdered')

women_df$year = as.numeric(women_df$year)

readr::write_csv(x = women_df, 'cleaned_murdered_women_per_100000_people.csv')

women_murdered_filtered = 
  women_df |> # dataset read in previous lines of code
  dplyr::filter(
    country == 'United States' &
    year > 2000
    )

women_murdered_filtered2 =   women_murdered_filtered

women_murdered_filtered2['lag'] =  dplyr::lag(women_murdered_filtered2['women_murdered'])
women_murdered_filtered2['diff1a'] =  women_murdered_filtered2['women_murdered'] - women_murdered_filtered2['lag']

women_murdered_filtered = 
  women_murdered_filtered |> 
  dplyr::mutate(
    # the first lag
    lag = dplyr::lag(women_murdered),
    # your first difference: transformation to stabilize the mean
    # diff1a and diff1b are identical
    diff1a = women_murdered - lag,
    diff1b = c(NA, diff(women_murdered) ),
    # transformations to stablize the variance
    log_murders = log(women_murdered),
    sqrt_murders = sqrt(women_murdered),
    # stablize both the mean and variance
    murders_0_1 = (women_murdered - min(women_murdered) )/ (max(women_murdered) - min(women_murdered))
  )
  
```

